services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
      MYSQL_USER: iseeanoob
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql







  node-app:
    build: ./rabakt-helpdesk
    container_name: node_app
    restart: always
    environment:
      JWT_SECRET: your_jwt_secret
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: pass
      DB_NAME: mydb
    ports:
      - "3000:3000"
    depends_on:
      - db

  go-app:
    build: ./go-backend
    container_name: go_app
    restart: always
    expose:
      - "5000"

  gateway:
    build: ./api_gateway
    container_name: api_gateway
    restart: always
    ports:
      - "80:80"          # FIXED â€” Nginx listens on port 80
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-app
      - go-app

volumes:
  db_data:
