version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
      MYSQL_USER: iseeanoob
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  auth:
    build: ./authentication
    container_name: auth_service
    restart: always
    environment:
      PORT: 3000
      JWT_SECRET: your_jwt_secret
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: pass
      DB_NAME: mydb
    expose:
      - "3000"
    depends_on:
      - db

  node-app:
    build: ./r√•bakt-helpdesk
    container_name: node_app
    restart: always
    environment:
      PORT: 3001
      JWT_SECRET: your_jwt_secret
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: pass
      DB_NAME: mydb
    expose:
      - "3001"
    depends_on:
      - db
      - auth

  go-app:
    build: ./go-backend
    container_name: go_app
    restart: always
    expose:
      - "8080"

  gateway:
    image: nginx:latest
    container_name: api_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - node-app
      - go-app

volumes:
  db_data:
